config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user! , except: [:index, :show]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand navbar_styling" style="font-weight: bold; color: rgb(91, 243, 254)" href="#">Editing Project</a>
  <p class="nav-link" style="color: rgba(91, 243, 254, 1); padding-left: 24%"><%= notice %></p>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div style="padding-left: 80%">
      <ul class="navbar-nav mr-auto" style="margin-bottom: -18px">
        <li class="nav-item">
          <p class="nav-link" style="color: rgba(91, 243, 254, 1)"><%= link_to "Home", root_path %></p>
        </li>
        <li class="nav-item">
        <% if user_signed_in? %>
          <a class="nav-link" rel="nofollow" data-method="delete" href="/users/sign_out" style="color: rgba(91, 243, 254, 1)">Logout</a>
        <% end %>
        <% if !user_signed_in? %>
          <a class="nav-link" style="color: rgba(91, 243, 254, 1);" href="/users/sign_in">Sign in</a>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<br>

<div style="padding-left: 75px">
  <div style="font-weight: bold">
    <%= render 'form', project: @project %>
  </div>
</div>

<div class="btn-group" style="float: right">
  <button type="button" class="btn btn-sm btn-outline-secondary button_text" style="background-color: black"><%= link_to 'View', @project %></button>
  <button type="button" class="btn btn-sm btn-outline-secondary button_text" style="background-color: black"><%= link_to 'Back', projects_path %></button>
</div>

app/views/projects/index.html.erb
<div class="background_display">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<a class="navbar-brand navbar_styling" style="font-weight: bold; color: rgb(91, 243, 254)" href="#">My Project Portfolio</a>
  <p class="nav-link" style="color: rgba(91, 243, 254, 1); padding-left: 24%"><%= notice %></p>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div style="padding-left: 80%">
      <ul class="navbar-nav mr-auto" style="margin-bottom: -18px">
        <li class="nav-item">
          <p class="nav-link" style="color: rgba(91, 243, 254, 1)"><%= link_to "Home", root_path %></p>
        </li>
        <li class="nav-item">
        <% if user_signed_in? %>
          <a class="nav-link" rel="nofollow" data-method="delete" href="/users/sign_out" style="color: rgba(91, 243, 254, 1)">Logout</a>
        <% end %>
        <% if !user_signed_in? %>
          <a class="nav-link" style="color: rgba(91, 243, 254, 1);" href="/users/sign_in">Sign in</a>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>


<div class="container">
<div class="row">
<% @projects.each do |project| %>
  <div class="card card_padding" style="width: 18rem; height: 450px; overflow: hidden;">
    <div class="card-body" style="background-color: rgba(255, 255, 255, 1">
      <p class="card-text" style="background-color: rgba(91, 243, 254, 1); font-weight: bold; padding-left: 3%"><%= project.title %></p>
      <p class="card-text" style="overflow: hidden; max-height: 90%"><%= project.description %></p>
    </div>
    <div class="btn-group a" style="background-color: black; display: flex;">
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "View", project %></button>
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_project_path(project) %></button>
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Delete", project, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </div>
  </div>
  <% end %>
</div>
</div>
<br>

<button type="button" class="btn btn-sm btn-outline-secondary button_text" style="background-color: black"><%= link_to "Project Overview", '/images/ProjectOverview.mp4' %></button>
<div class="btn-group" style="float: right">
  <button type="button" class="btn btn-sm btn-outline-secondary button_text" style="background-color: black"><%= link_to "New Project", new_project_path %></button>
  <button type="button" class="btn btn-sm btn-outline-secondary button_text" style="background-color: black"><%= link_to "Logout", destroy_user_session_path, method: :delete %></button>
</div>

</div>

app/views/projects/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<a class="navbar-brand navbar_styling" style="font-weight: bold; color: rgb(91, 243, 254)" href="#">New Project</a>
  <p class="nav-link" style="color: rgba(91, 243, 254, 1); padding-left: 24%"><%= notice %></p>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div style="padding-left: 80%">
      <ul class="navbar-nav mr-auto" style="margin-bottom: -18px">
        <li class="nav-item">
          <p class="nav-link" style="color: rgba(91, 243, 254, 1)"><%= link_to "Home", root_path %></p>
        </li>
        <li class="nav-item">
        <% if user_signed_in? %>
          <a class="nav-link" rel="nofollow" data-method="delete" href="/users/sign_out" style="color: rgba(91, 243, 254, 1)">Logout</a>
        <% end %>
        <% if !user_signed_in? %>
          <a class="nav-link" style="color: rgba(91, 243, 254, 1);" href="/users/sign_in">Sign in</a>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<br>


<div style="padding-left: 75px">
  <%= render 'form', project: @project %>
</div>

<div class="btn-group" style="float: right">
  <button type="button" class="btn btn-sm btn-outline-secondary button_text" style="background-color: black"><%= link_to 'Back', projects_path %></button>
</div>

app/views/projects/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand navbar_styling" style="font-weight: bold; color: rgb(91, 243, 254)" href="#">Showing Project</a>
  <p class="nav-link" style="color: rgba(91, 243, 254, 1); padding-left: 24%"><%= notice %></p>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div style="padding-left: 80%">
      <ul class="navbar-nav mr-auto" style="margin-bottom: -18px">
        <li class="nav-item">
          <p class="nav-link" style="color: rgba(91, 243, 254, 1)"><%= link_to "Home", root_path %></p>
        </li>
        <li class="nav-item">
        <% if user_signed_in? %>
          <a class="nav-link" rel="nofollow" data-method="delete" href="/users/sign_out" style="color: rgba(91, 243, 254, 1)">Logout</a>
        <% end %>
        <% if !user_signed_in? %>
          <a class="nav-link" style="color: rgba(91, 243, 254, 1);" href="/users/sign_in">Sign in</a>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<br>


<p style="font-size: 30px; color: black; padding-top: 0.5rem; padding-left: 75px; padding-bottom: 0.5rem">
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p style="padding-left: 75px">
  <strong style="font-size: larger">Description:</strong>
  <p style="font-size: larger; padding-left: 75px; padding-right: 65px"><%= @project.description %></p>
</p>

<div class="btn-group" style="float: right">
  <button type="button" class="btn btn-sm btn-outline-secondary button_text" style="background-color: black"><%= link_to 'Edit', edit_project_path(@project) %></button>
  <button type="button" class="btn btn-sm btn-outline-secondary button_text" style="background-color: black"><%= link_to 'Back', projects_path %></button>
</div>